import type { PrismaClient } from '@prisma/client';
import type { AgentExecution } from '@/lib/agents';
import type { ApprovalDecision, PipelineRun } from '@/lib/orchestration';
import type { Character, CharacterInput, ContinuityFact, Episode, EpisodeInput, GeneratedAsset, GenerationJob, Location, LocationInput, Scene, SceneInput, Series, Shot, ShotInput, Storyboard, StoryFact, StoryFactInput } from '@/types';
import type { PersistedUser, PersistenceRepository, ProductionMembershipRecord, RepositoryRole, PipelineStageStatus, SeriesInput } from './contracts';
import { EMPIRE_OF_LIES_SERIES, createEmpireOfLiesEpisodes } from '@/lib/mock';

export class PrismaPersistenceRepository implements PersistenceRepository {
  constructor(private readonly db: PrismaClient) {}

  async getUser(id: string): Promise<PersistedUser | undefined> {
    const user = await this.db.user.findUnique({ where: { id } });
    return user ? { id: user.id, email: user.email, displayName: user.displayName, provider: user.provider, providerSubject: user.providerSubject } : undefined;
  }
  async findUserByEmail(email: string): Promise<PersistedUser | undefined> { const user = await this.db.user.findUnique({ where: { email } }); return user ? { id: user.id, email: user.email, displayName: user.displayName, provider: user.provider, providerSubject: user.providerSubject } : undefined; }
  async upsertUser(user: PersistedUser): Promise<PersistedUser> {
    const value = await this.db.user.upsert({ where: { id: user.id }, create: user, update: { email: user.email, displayName: user.displayName, provider: user.provider, providerSubject: user.providerSubject } });
    return { id: value.id, email: value.email, displayName: value.displayName, provider: value.provider, providerSubject: value.providerSubject };
  }
  async upsertUserIdentity(user: Omit<PersistedUser, 'id'>): Promise<PersistedUser> {
    const byEmail = await this.db.user.findUnique({ where: { email: user.email } });
    if (byEmail) {
      const linked = await this.db.user.update({ where: { id: byEmail.id }, data: { displayName: user.displayName, provider: user.provider, providerSubject: user.providerSubject } });
      return { id: linked.id, email: linked.email, displayName: linked.displayName, provider: linked.provider, providerSubject: linked.providerSubject };
    }
    const value = await this.db.user.upsert({ where: { provider_providerSubject: { provider: user.provider, providerSubject: user.providerSubject } }, create: { ...user, id: `user_${user.provider}_${user.providerSubject}`.replace(/[^a-zA-Z0-9_-]/g, '_') }, update: { email: user.email, displayName: user.displayName } });
    return { id: value.id, email: value.email, displayName: value.displayName, provider: value.provider, providerSubject: value.providerSubject };
  }
  async getMembership(userId: string, seriesId: string): Promise<ProductionMembershipRecord | undefined> {
    if (seriesId === EMPIRE_OF_LIES_SERIES.id) await this.ensureDemoProduction(userId);
    const value = await this.db.productionMembership.findUnique({ where: { userId_seriesId: { userId, seriesId } } });
    return value ? { id: value.id, userId: value.userId, seriesId: value.seriesId, role: value.role as RepositoryRole } : undefined;
  }
  async upsertMembership(record: ProductionMembershipRecord): Promise<ProductionMembershipRecord> {
    const value = await this.db.productionMembership.upsert({ where: { userId_seriesId: { userId: record.userId, seriesId: record.seriesId } }, create: { id: record.id, userId: record.userId, seriesId: record.seriesId, role: record.role }, update: { role: record.role } });
    return { id: value.id, userId: value.userId, seriesId: value.seriesId, role: value.role as RepositoryRole };
  }
  async listMemberships(seriesId: string): Promise<ProductionMembershipRecord[]> { const values = await this.db.productionMembership.findMany({ where: { seriesId } }); return values.map((value) => ({ id: value.id, userId: value.userId, seriesId: value.seriesId, role: value.role as RepositoryRole })); }
  async removeMembership(userId: string, seriesId: string): Promise<void> { await this.db.productionMembership.delete({ where: { userId_seriesId: { userId, seriesId } } }); }
  async listAccessibleSeries(userId: string): Promise<Series[]> { const values = await this.db.series.findMany({ where: { memberships: { some: { userId } } }, include: { characters: true, episodes: true } }); return values.map((value) => this.toSeries(value)); }
  async getSeries(seriesId: string): Promise<Series | undefined> { const value = await this.db.series.findUnique({ where: { id: seriesId }, include: { characters: true, episodes: true } }); return value ? this.toSeries(value) : undefined; }
  async createSeries(ownerId: string, input: SeriesInput): Promise<Series> { const value = await this.db.series.create({ data: { id: `series_${Date.now()}`, title: input.title, logline: input.logline, genre: input.genre, targetAudience: input.targetAudience, visualStyle: input.visualStyle, episodeCount: input.episodeCount, episodeDurationSeconds: input.episodeDurationSeconds, status: input.status || 'draft', ownerId, memberships: { create: { id: `membership_${Date.now()}`, userId: ownerId, role: 'OWNER' } } }, include: { characters: true, episodes: true } }); return this.toSeries(value); }
  async updateSeries(seriesId: string, input: Partial<SeriesInput>): Promise<Series> { const value = await this.db.series.update({ where: { id: seriesId }, data: input, include: { characters: true, episodes: true } }); return this.toSeries(value); }
  async archiveSeries(seriesId: string): Promise<Series> { return this.updateSeries(seriesId, { status: 'archived' }); }
  async listCharacters(seriesId: string): Promise<Character[]> { const values = await this.db.character.findMany({ where: { seriesId } }); return values.map((value) => this.toCharacter(value)); }
  async getCharacter(seriesId: string, characterId: string): Promise<Character | undefined> { const value = await this.db.character.findFirst({ where: { id: characterId, seriesId } }); return value ? this.toCharacter(value) : undefined; }
  async createCharacter(seriesId: string, input: CharacterInput): Promise<Character> { const value = await this.db.character.create({ data: { id: `character_${Date.now()}`, seriesId, name: input.name, role: input.role, description: input.description, age: input.age, ageRange: input.ageRange, appearance: input.appearance, wardrobe: input.wardrobe, personality: input.personality, relationships: [], voiceProfile: input.voiceProfile as unknown as object, continuityNotes: input.continuityNotes || [], status: input.status || 'active' } }); return this.toCharacter(value); }
  async updateCharacter(seriesId: string, characterId: string, input: Partial<CharacterInput>): Promise<Character> { const value = await this.db.character.update({ where: { id: characterId }, data: { ...input, voiceProfile: input.voiceProfile as unknown as object, continuityNotes: input.continuityNotes } }); if (value.seriesId !== seriesId) throw new Error(`Character ${characterId} was not found`); return this.toCharacter(value); }
  async deleteCharacter(seriesId: string, characterId: string): Promise<void> { if (!(await this.getCharacter(seriesId, characterId))) throw new Error(`Character ${characterId} was not found`); await this.db.character.delete({ where: { id: characterId } }); }
  async listLocations(seriesId: string): Promise<Location[]> { const values = await this.db.location.findMany({ where: { seriesId } }); return values.map((value) => this.toLocation(value)); }
  async getLocation(seriesId: string, locationId: string): Promise<Location | undefined> { const value = await this.db.location.findFirst({ where: { id: locationId, seriesId } }); return value ? this.toLocation(value) : undefined; }
  async createLocation(seriesId: string, input: LocationInput): Promise<Location> { const value = await this.db.location.create({ data: { id: `location_${Date.now()}`, seriesId, name: input.name, description: input.description, type: input.type, visualDescription: input.visualDescription, roomDetails: input.roomDetails, lighting: input.lighting, visualStyle: input.visualStyle, props: [], continuityNotes: input.continuityNotes || [] } }); return this.toLocation(value); }
  async updateLocation(seriesId: string, locationId: string, input: Partial<LocationInput>): Promise<Location> { const value = await this.db.location.update({ where: { id: locationId }, data: input }); if (value.seriesId !== seriesId) throw new Error(`Location ${locationId} was not found`); return this.toLocation(value); }
  async deleteLocation(seriesId: string, locationId: string): Promise<void> { if (!(await this.getLocation(seriesId, locationId))) throw new Error(`Location ${locationId} was not found`); await this.db.location.delete({ where: { id: locationId } }); }
  async listEpisodes(seriesId: string): Promise<Episode[]> { const values = await this.db.episode.findMany({ where: { seriesId }, include: { scenes: true } }); return values.map((value) => this.toEpisode(value)); }
  async getEpisode(seriesId: string, episodeId: string): Promise<Episode | undefined> { const value = await this.db.episode.findFirst({ where: { id: episodeId, seriesId }, include: { scenes: true } }); return value ? this.toEpisode(value) : undefined; }
  async createEpisode(seriesId: string, input: EpisodeInput): Promise<Episode> { const value = await this.db.episode.create({ data: { id: `episode_${Date.now()}`, seriesId, episodeNumber: input.episodeNumber, title: input.title, hook: input.hook || '', synopsis: input.synopsis, cliffhanger: input.cliffhanger || '', status: input.status || 'draft', estimatedDurationSeconds: input.estimatedDurationSeconds }, include: { scenes: true } }); return this.toEpisode(value); }
  async updateEpisode(seriesId: string, episodeId: string, input: Partial<EpisodeInput>): Promise<Episode> { const value = await this.db.episode.update({ where: { id: episodeId }, data: input, include: { scenes: true } }); if (value.seriesId !== seriesId) throw new Error(`Episode ${episodeId} was not found`); return this.toEpisode(value); }
  async deleteEpisode(seriesId: string, episodeId: string): Promise<void> { if (!(await this.getEpisode(seriesId, episodeId))) throw new Error(`Episode ${episodeId} was not found`); await this.db.episode.delete({ where: { id: episodeId } }); }
  async listScenes(seriesId: string, episodeId: string): Promise<Scene[]> { if (!(await this.getEpisode(seriesId, episodeId))) throw new Error(`Episode ${episodeId} was not found`); const values = await this.db.scene.findMany({ where: { episodeId }, include: { shots: true } }); return values.map((value) => this.toScene(value)); }
  async getScene(seriesId: string, episodeId: string, sceneId: string): Promise<Scene | undefined> { if (!(await this.getEpisode(seriesId, episodeId))) return undefined; const value = await this.db.scene.findFirst({ where: { id: sceneId, episodeId }, include: { shots: true } }); return value ? this.toScene(value) : undefined; }
  async createScene(seriesId: string, episodeId: string, input: SceneInput): Promise<Scene> { if (!(await this.getEpisode(seriesId, episodeId))) throw new Error(`Episode ${episodeId} was not found`); if (input.locationId && !(await this.getLocation(seriesId, input.locationId))) throw new Error('Location must belong to the production'); const value = await this.db.scene.create({ data: { id: `scene_${Date.now()}`, episodeId, sceneNumber: input.sceneNumber, title: input.title, description: input.description, locationId: input.locationId || '', timeOfDay: input.timeOfDay, estimatedDurationSeconds: input.estimatedDurationSeconds, status: input.status || 'draft' }, include: { shots: true } }); return this.toScene(value); }
  async updateScene(seriesId: string, episodeId: string, sceneId: string, input: Partial<SceneInput>): Promise<Scene> { if (input.locationId && !(await this.getLocation(seriesId, input.locationId))) throw new Error('Location must belong to the production'); const value = await this.db.scene.update({ where: { id: sceneId }, data: input, include: { shots: true } }); if (value.episodeId !== episodeId) throw new Error(`Scene ${sceneId} was not found`); return this.toScene(value); }
  async deleteScene(seriesId: string, episodeId: string, sceneId: string): Promise<void> { if (!(await this.getScene(seriesId, episodeId, sceneId))) throw new Error(`Scene ${sceneId} was not found`); await this.db.scene.delete({ where: { id: sceneId } }); }
  async listStoryFacts(seriesId: string): Promise<StoryFact[]> { const values = await this.db.storyFact.findMany({ where: { seriesId } }); return values.map((value) => this.toStoryFact(value)); }
  async createStoryFact(seriesId: string, input: StoryFactInput): Promise<StoryFact> { if (input.episodeId && !(await this.getEpisode(seriesId, input.episodeId))) throw new Error('Episode must belong to the production'); const value = await this.db.storyFact.create({ data: { id: `story_fact_${Date.now()}`, seriesId, episodeId: input.episodeId, sceneId: input.sceneId, subjectType: input.subjectType, subjectId: input.subjectId, category: input.category, description: input.description, validFromEpisode: input.validFromEpisode, validUntilEpisode: input.validUntilEpisode, source: input.source, confidence: input.confidence, metadata: (input.metadata || {}) as object } }); return this.toStoryFact(value); }
  async updateStoryFact(seriesId: string, factId: string, input: Partial<StoryFactInput>): Promise<StoryFact> { const value = await this.db.storyFact.update({ where: { id: factId }, data: { ...input, metadata: input.metadata as object } }); if (value.seriesId !== seriesId) throw new Error(`Story fact ${factId} was not found`); return this.toStoryFact(value); }
  async deleteStoryFact(seriesId: string, factId: string): Promise<void> { if (!(await this.db.storyFact.findFirst({ where: { id: factId, seriesId } }))) throw new Error(`Story fact ${factId} was not found`); await this.db.storyFact.delete({ where: { id: factId } }); }
  async listShots(seriesId: string, episodeId: string, sceneId: string): Promise<Shot[]> { const scene = await this.db.scene.findFirst({ where: { id: sceneId, episodeId, episode: { seriesId } } }); if (!scene) throw new Error(`Scene ${sceneId} was not found`); const values = await this.db.shot.findMany({ where: { seriesId, episodeId, sceneId }, orderBy: { shotNumber: 'asc' } }); return values.map((value) => this.toShot(value)); }
  async getShot(seriesId: string, episodeId: string, sceneId: string, shotId: string): Promise<Shot | undefined> { const value = await this.db.shot.findFirst({ where: { id: shotId, seriesId, episodeId, sceneId } }); return value ? this.toShot(value) : undefined; }
  async createShot(seriesId: string, episodeId: string, sceneId: string, input: ShotInput): Promise<Shot> { const scene = await this.db.scene.findFirst({ where: { id: sceneId, episodeId, episode: { seriesId } } }); if (!scene) throw new Error(`Scene ${sceneId} was not found`); const value = await this.db.shot.create({ data: { id: `shot_${Date.now()}`, seriesId, episodeId, sceneId, shotNumber: input.shotNumber, title: input.title, shotType: input.shotType, cameraAngle: input.cameraAngle, framing: input.framing || 'medium', cameraMovement: input.cameraMovement || 'static', description: input.description, dialogue: input.dialogue, durationSeconds: input.durationSeconds, characterIds: input.characterIds || [], locationId: input.locationId || scene.locationId, continuityRequirements: [], visualPrompt: input.visualPrompt, negativePrompt: input.negativePrompt, continuityNotes: input.continuityNotes || [], status: input.status || 'draft' } }); return this.toShot(value); }
  async updateShot(seriesId: string, episodeId: string, sceneId: string, shotId: string, input: Partial<ShotInput>): Promise<Shot> { const current = await this.getShot(seriesId, episodeId, sceneId, shotId); if (!current) throw new Error(`Shot ${shotId} was not found`); const value = await this.db.shot.update({ where: { id: shotId }, data: { ...input, continuityNotes: input.continuityNotes, characterIds: input.characterIds, visualPrompt: input.visualPrompt } }); return this.toShot(value); }
  async deleteShot(seriesId: string, episodeId: string, sceneId: string, shotId: string): Promise<void> { if (!(await this.getShot(seriesId, episodeId, sceneId, shotId))) throw new Error(`Shot ${shotId} was not found`); await this.db.shot.delete({ where: { id: shotId } }); }
  async reorderShots(seriesId: string, episodeId: string, sceneId: string, shotIds: string[]): Promise<Shot[]> { const shots = await this.listShots(seriesId, episodeId, sceneId); if (shots.length !== shotIds.length || shots.some((shot) => !shotIds.includes(shot.id))) throw new Error('Shot reorder must include every shot in the scene exactly once'); await this.db.$transaction(shotIds.map((id, index) => this.db.shot.update({ where: { id }, data: { shotNumber: index + 1 } }))); return this.listShots(seriesId, episodeId, sceneId); }
  async getStoryboard(seriesId: string, episodeId: string, sceneId: string, shotId: string): Promise<Storyboard | undefined> { const shot = await this.getShot(seriesId, episodeId, sceneId, shotId); if (!shot) return undefined; const value = await this.db.storyboard.findUnique({ where: { shotId } }); return value ? this.toStoryboard(value) : undefined; }
  async createStoryboard(seriesId: string, episodeId: string, sceneId: string, shotId: string): Promise<Storyboard> { const shot = await this.getShot(seriesId, episodeId, sceneId, shotId); if (!shot) throw new Error(`Shot ${shotId} was not found`); const value = await this.db.storyboard.upsert({ where: { shotId }, create: { id: `storyboard_${shotId}`, shotId, prompt: shot.visualPrompt || shot.description, generationStatus: 'placeholder', provider: 'mock', width: 720, height: 1280, aspectRatio: '9:16' }, update: { prompt: shot.visualPrompt || shot.description, updatedAt: new Date() } }); return this.toStoryboard(value); }
  async listAllShots(seriesId: string): Promise<Shot[]> { const values = await this.db.shot.findMany({ where: { seriesId }, orderBy: { shotNumber: 'asc' } }); return values.map((value) => this.toShot(value)); }
  async createGenerationJob(job: GenerationJob): Promise<GenerationJob> { await this.db.generationJob.create({ data: job as never }); return job; }
  async updateGenerationJob(job: GenerationJob): Promise<GenerationJob> { await this.db.generationJob.update({ where: { id: job.id }, data: job as never }); return job; }
  async getGenerationJob(seriesId: string, episodeId: string, sceneId: string, shotId: string, jobId: string): Promise<GenerationJob | undefined> { const value = await this.db.generationJob.findFirst({ where: { id: jobId, seriesId, episodeId, sceneId, shotId } }); return value ? value as unknown as GenerationJob : undefined; }
  async listGenerationJobs(seriesId: string, episodeId: string, sceneId: string, shotId: string): Promise<GenerationJob[]> { const values = await this.db.generationJob.findMany({ where: { seriesId, episodeId, sceneId, shotId } }); return values as unknown as GenerationJob[]; }
  async createGeneratedAsset(asset: GeneratedAsset): Promise<GeneratedAsset> { await this.db.generatedAsset.create({ data: asset as never }); return asset; }
  async listGeneratedAssets(seriesId: string, episodeId: string, sceneId: string, shotId: string): Promise<GeneratedAsset[]> { const values = await this.db.generatedAsset.findMany({ where: { seriesId, episodeId, sceneId, shotId } }); return values as unknown as GeneratedAsset[]; }
  async create(pipeline: PipelineRun): Promise<PipelineRun> { await this.db.pipelineRun.create({ data: { id: pipeline.id, seriesId: pipeline.seriesId, episodeId: pipeline.episodeId, initiatedById: pipeline.initiatedById, state: pipeline.state, output: pipeline as object, error: pipeline.error } }); return pipeline; }
  async get(id: string): Promise<PipelineRun | undefined> { const value = await this.db.pipelineRun.findUnique({ where: { id } }); return value?.output ? value.output as unknown as PipelineRun : undefined; }
  async update(pipeline: PipelineRun): Promise<PipelineRun> { await this.db.pipelineRun.update({ where: { id: pipeline.id }, data: { state: pipeline.state, output: pipeline as object, generationJobId: pipeline.generationJobId, error: pipeline.error } }); return pipeline; }
  async listExecutions(pipelineId?: string): Promise<AgentExecution[]> { const values = await this.db.agentExecution.findMany({ where: pipelineId ? { pipelineId } : undefined, orderBy: { timestamp: 'asc' } }); return values.map((value) => ({ id: value.id, agent: value.agent as AgentExecution['agent'], seriesId: value.seriesId, episodeId: value.episodeId || undefined, input: value.input, output: value.output || undefined, status: value.status.toLowerCase() as AgentExecution['status'], confidence: value.confidence || undefined, explanation: value.explanation || undefined, timestamp: value.timestamp, durationMs: value.durationMs, errors: value.errors as unknown as AgentExecution['errors'], metadata: value.metadata as unknown as AgentExecution['metadata'] })); }
  async saveExecution(execution: AgentExecution, pipelineId: string): Promise<AgentExecution> { await this.db.agentExecution.create({ data: { id: execution.id, pipelineId, agent: execution.agent, seriesId: execution.seriesId, episodeId: execution.episodeId, input: execution.input as object, output: execution.output as object, status: execution.status.toUpperCase() as 'QUEUED' | 'RUNNING' | 'SUCCEEDED' | 'FAILED', confidence: execution.confidence, explanation: execution.explanation, timestamp: execution.timestamp, durationMs: execution.durationMs, errors: execution.errors as object, metadata: execution.metadata as object } }); return execution; }
  async saveApproval(approval: ApprovalDecision): Promise<ApprovalDecision> { await this.db.approvalDecision.upsert({ where: { id: approval.id }, create: { id: approval.id, pipelineId: approval.pipelineId, status: approval.status.toUpperCase() as 'PENDING' | 'APPROVED' | 'REJECTED' | 'REVISION_REQUESTED', requestedAction: approval.requestedAction, summary: approval.summary, projectedImpact: approval.projectedImpact, requestedAt: approval.requestedAt, decisionAt: approval.decisionAt, decisionNote: approval.decisionNote }, update: { status: approval.status.toUpperCase() as 'PENDING' | 'APPROVED' | 'REJECTED' | 'REVISION_REQUESTED', decisionAt: approval.decisionAt, decisionNote: approval.decisionNote } }); return approval; }
  async saveStage(pipelineId: string, stageKey: string, status: PipelineStageStatus, output?: unknown, metadata: Record<string, string | number | boolean> = {}): Promise<void> { await this.db.pipelineStage.upsert({ where: { pipelineId_stageKey: { pipelineId, stageKey } }, create: { id: `stage_${pipelineId}_${stageKey}`, pipelineId, stageKey, status, output: output as object, metadata }, update: { status, output: output as object, metadata } }); }
  async addFact(fact: ContinuityFact): Promise<ContinuityFact> { await this.db.seriesMemoryFact.upsert({ where: { id: fact.id }, create: { ...fact, subjectType: fact.subjectType, override: fact.override ?? false }, update: { value: fact.value, validToEpisode: fact.validToEpisode, validToScene: fact.validToScene, validToShot: fact.validToShot, confidence: fact.confidence, override: fact.override ?? false } }); return fact; }
  async listFacts(seriesId: string): Promise<ContinuityFact[]> { const values = await this.db.seriesMemoryFact.findMany({ where: { seriesId } }); return values.map((value) => ({ id: value.id, seriesId: value.seriesId, subjectType: value.subjectType as ContinuityFact['subjectType'], subjectId: value.subjectId, key: value.key, value: value.value, validFromEpisode: value.validFromEpisode, validFromScene: value.validFromScene ?? undefined, validFromShot: value.validFromShot ?? undefined, validToEpisode: value.validToEpisode ?? undefined, validToScene: value.validToScene ?? undefined, validToShot: value.validToShot ?? undefined, source: value.source, confidence: value.confidence, override: value.override, createdAt: value.createdAt, updatedAt: value.updatedAt })); }
  async getActiveFacts(seriesId: string, episodeNumber: number, sceneNumber?: number, shotNumber?: number): Promise<ContinuityFact[]> { const facts = await this.listFacts(seriesId); return facts.filter((fact) => episodeNumber >= fact.validFromEpisode && (fact.validToEpisode === undefined || episodeNumber <= fact.validToEpisode) && (fact.validFromScene === undefined || sceneNumber === undefined || episodeNumber !== fact.validFromEpisode || sceneNumber >= fact.validFromScene) && (fact.validToScene === undefined || sceneNumber === undefined || episodeNumber !== fact.validToEpisode || sceneNumber <= fact.validToScene) && (fact.validFromShot === undefined || shotNumber === undefined || shotNumber >= fact.validFromShot) && (fact.validToShot === undefined || shotNumber === undefined || shotNumber <= fact.validToShot)); }
  async reset(): Promise<void> { throw new Error('Reset is not supported by the Prisma repository'); }

  private async ensureDemoProduction(ownerId: string): Promise<void> {
    await this.db.series.upsert({ where: { id: EMPIRE_OF_LIES_SERIES.id }, create: { id: EMPIRE_OF_LIES_SERIES.id, title: EMPIRE_OF_LIES_SERIES.title, logline: EMPIRE_OF_LIES_SERIES.logline, genre: EMPIRE_OF_LIES_SERIES.genre, targetAudience: EMPIRE_OF_LIES_SERIES.targetAudience, visualStyle: EMPIRE_OF_LIES_SERIES.visualStyle, episodeCount: EMPIRE_OF_LIES_SERIES.episodeCount, episodeDurationSeconds: EMPIRE_OF_LIES_SERIES.episodeDurationSeconds, status: EMPIRE_OF_LIES_SERIES.status, ownerId }, update: {} });
    for (const episode of createEmpireOfLiesEpisodes()) {
      await this.db.episode.upsert({ where: { seriesId_episodeNumber: { seriesId: EMPIRE_OF_LIES_SERIES.id, episodeNumber: episode.episodeNumber } }, create: { id: episode.id, seriesId: EMPIRE_OF_LIES_SERIES.id, episodeNumber: episode.episodeNumber, title: episode.title, hook: episode.hook, synopsis: episode.synopsis, cliffhanger: episode.cliffhanger }, update: { title: episode.title, hook: episode.hook, synopsis: episode.synopsis, cliffhanger: episode.cliffhanger } });
    }
  }
  private toSeries(value: { id: string; title: string; logline: string; genre: string; targetAudience: string; visualStyle: string; episodeCount: number; episodeDurationSeconds: number; status: string; createdAt: Date; updatedAt: Date; characters: Array<{ id: string; seriesId: string; name: string; role: string; age: number; appearance: string; wardrobe: string; personality: string; relationships: unknown; voiceProfile: unknown; continuityNotes: string[]; createdAt: Date; updatedAt: Date }>; episodes: Array<{ id: string; seriesId: string; episodeNumber: number; title: string; hook: string; synopsis: string; cliffhanger: string; createdAt: Date; updatedAt: Date }> }): Series {
    return { id: value.id, title: value.title, logline: value.logline, genre: value.genre, targetAudience: value.targetAudience, visualStyle: value.visualStyle, episodeCount: value.episodeCount, episodeDurationSeconds: value.episodeDurationSeconds, status: value.status as Series['status'], characters: value.characters.map((character) => ({ ...character, role: character.role as never, relationships: character.relationships as never, voiceProfile: character.voiceProfile as never })), episodes: value.episodes.map((episode) => ({ ...episode, scenes: [] })), createdAt: value.createdAt, updatedAt: value.updatedAt };
  }
  private toCharacter(value: { id: string; seriesId: string; name: string; role: string; description: string | null; age: number; ageRange: string | null; appearance: string; wardrobe: string; personality: string; relationships: unknown; voiceProfile: unknown; continuityNotes: string[]; status: string; createdAt: Date; updatedAt: Date }): Character { return { ...value, role: value.role as Character['role'], description: value.description || undefined, ageRange: value.ageRange || undefined, relationships: value.relationships as Character['relationships'], voiceProfile: value.voiceProfile as Character['voiceProfile'], status: value.status as Character['status'] }; }
  private toLocation(value: { id: string; seriesId: string; name: string; description: string; type: string | null; visualDescription: string | null; roomDetails: string | null; lighting: string | null; visualStyle: string | null; props: unknown; continuityNotes: string[]; createdAt: Date; updatedAt: Date }): Location { return { ...value, type: value.type || undefined, visualDescription: value.visualDescription || undefined, roomDetails: value.roomDetails || undefined, lighting: value.lighting || undefined, visualStyle: value.visualStyle || undefined, props: value.props as Location['props'], continuityNotes: value.continuityNotes }; }
  private toEpisode(value: { id: string; seriesId: string; episodeNumber: number; title: string; hook: string; synopsis: string; cliffhanger: string; status: string; estimatedDurationSeconds: number | null; createdAt: Date; updatedAt: Date; scenes: Array<Record<string, unknown>> }): Episode { return { ...value, status: value.status as Episode['status'], estimatedDurationSeconds: value.estimatedDurationSeconds || undefined, scenes: value.scenes.map((scene) => scene as unknown as Scene) }; }
  private toScene(value: { id: string; episodeId: string; sceneNumber: number; title: string; description: string; locationId: string; timeOfDay: string | null; estimatedDurationSeconds: number | null; status: string; createdAt: Date; updatedAt: Date; shots: unknown[] }): Scene { return { id: value.id, episodeId: value.episodeId, sceneNumber: value.sceneNumber, title: value.title, description: value.description, locationId: value.locationId, timeOfDay: value.timeOfDay || undefined, estimatedDurationSeconds: value.estimatedDurationSeconds || undefined, status: value.status as Scene['status'], shots: value.shots as Scene['shots'], characterIds: [], createdAt: value.createdAt, updatedAt: value.updatedAt }; }
  private toStoryFact(value: { id: string; seriesId: string; episodeId: string | null; sceneId: string | null; subjectType: string; subjectId: string | null; category: string; description: string; validFromEpisode: number | null; validUntilEpisode: number | null; source: string; confidence: number | null; metadata: unknown; createdAt: Date; updatedAt: Date }): StoryFact { return { id: value.id, seriesId: value.seriesId, type: value.category as StoryFact['type'], description: value.description, revealedInEpisode: value.validFromEpisode || undefined, affectedCharacterIds: value.subjectId ? [value.subjectId] : [], relatedFactIds: [], createdAt: value.createdAt, updatedAt: value.updatedAt }; }
  private toShot(value: { id: string; seriesId: string; episodeId: string; sceneId: string; shotNumber: number; title: string | null; shotType: string | null; cameraAngle: string | null; framing: string; cameraMovement: string; description: string; dialogue: string | null; durationSeconds: number; characterIds: string[]; locationId: string; continuityRequirements: unknown; visualPrompt: string; negativePrompt: string | null; continuityNotes: string[]; status: string; createdAt: Date; updatedAt: Date }): Shot { return { ...value, title: value.title || undefined, shotType: value.shotType as Shot['shotType'], cameraAngle: value.cameraAngle || undefined, framing: value.framing as Shot['framing'], cameraMovement: value.cameraMovement as Shot['cameraMovement'], dialogue: value.dialogue || undefined, negativePrompt: value.negativePrompt || undefined, continuityRequirements: value.continuityRequirements as Shot['continuityRequirements'], status: value.status as Shot['status'] }; }
  private toStoryboard(value: { id: string; shotId: string; prompt: string; referenceUrl: string | null; generationStatus: string; provider: string | null; generationJobId: string | null; width: number; height: number; aspectRatio: string; version: number; createdAt: Date; updatedAt: Date }): Storyboard { return { ...value, referenceUrl: value.referenceUrl || undefined, provider: value.provider || undefined, generationJobId: value.generationJobId || undefined, generationStatus: value.generationStatus as Storyboard['generationStatus'], aspectRatio: '9:16' }; }
}
