import 'server-only';

import { createHash } from 'node:crypto';
import type { AuthenticatedUser } from '@/lib/auth';
import { stableExportSerialize } from '@/lib/export/mock-engine';
import type { PersistenceRepository } from '@/lib/repositories';
import { ProductionService } from '@/lib/series';
import type { DeliveryManifest, EpisodeLaunchPackage } from '@/types';
import { ProductionReadinessService, preferredApprovedAssembly } from './readiness-service';
import { isSafeDeliveryUri } from './uri-safety';
import { consoleObservabilitySink, silentObservabilitySink, type ObservabilitySink } from '@/lib/observability';

interface PackageServiceOptions { now?: () => Date; readiness?: ProductionReadinessService; allowMockUris?: boolean; logger?: ObservabilitySink }

export class EpisodeLaunchPackageService {
  private readonly production: ProductionService;
  private readonly readiness: ProductionReadinessService;
  private readonly now: () => Date;
  private readonly allowMockUris: boolean;
  private readonly logger: ObservabilitySink;
  constructor(private readonly repository: PersistenceRepository, options: PackageServiceOptions = {}) { this.production = new ProductionService(repository); this.now = options.now || (() => new Date()); this.allowMockUris = options.allowMockUris ?? process.env.NODE_ENV === 'test'; this.readiness = options.readiness || new ProductionReadinessService(repository, { now: this.now, allowMockUris: this.allowMockUris }); this.logger = options.logger || (process.env.NODE_ENV === 'test' ? silentObservabilitySink : consoleObservabilitySink); }

  async list(user: AuthenticatedUser, seriesId: string, episodeId: string): Promise<EpisodeLaunchPackage[]> { await this.requireEpisode(user, seriesId, episodeId, 'VIEWER'); return this.repository.listEpisodeLaunchPackages(seriesId, episodeId); }
  async get(user: AuthenticatedUser, seriesId: string, episodeId: string, packageId: string): Promise<EpisodeLaunchPackage> { await this.requireEpisode(user, seriesId, episodeId, 'VIEWER'); return this.requirePackage(seriesId, episodeId, packageId); }

  async prepare(user: AuthenticatedUser, seriesId: string, episodeId: string): Promise<EpisodeLaunchPackage> {
    await this.requireEpisode(user, seriesId, episodeId, 'OWNER'); const series = await this.repository.getSeries(seriesId); const episode = await this.repository.getEpisode(seriesId, episodeId); if (!series || !episode) throw new Error('Series or episode was not found');
    const assembly = preferredApprovedAssembly(await this.repository.listEpisodeAssemblies(seriesId, episodeId)); if (!assembly) throw new Error('An approved, valid preferred assembly is required');
    const exportJob = (await this.repository.listEpisodeExportJobs(seriesId, episodeId)).filter((job) => job.assemblyId === assembly.id && job.status === 'completed').sort((a, b) => b.exportVersion - a.exportVersion)[0];
    if (!exportJob || exportJob.approvalState !== 'approved' || !exportJob.outputUri || !exportJob.outputFileName || !exportJob.durationMs || !exportJob.fileSize || !exportJob.checksum || !exportJob.completedAt) throw new Error('A completed approved export with delivery metadata is required');
    if (!isSafeDeliveryUri(exportJob.outputUri, this.allowMockUris) || (exportJob.sidecarUri && !isSafeDeliveryUri(exportJob.sidecarUri, this.allowMockUris))) throw new Error('Export output reference is unsafe');
    const readinessSnapshot = await this.readiness.episode(user, seriesId, episodeId); const rightsAttestations = await this.readiness.rightsAttestations(user, seriesId); const caption = assembly.captionTrackId ? await this.repository.getCaptionTrack(seriesId, episodeId, assembly.captionTrackId) : undefined; const assetStates: Array<Array<string | number | boolean>> = [];
    for (const item of assembly.items) for (const assetId of [item.videoAssetId, item.audioAssetId]) if (assetId) { const asset = await this.repository.getGeneratedAsset(seriesId, episodeId, item.sceneId, item.shotId, assetId); assetStates.push(asset ? [asset.id, asset.version, asset.reviewStatus, Boolean(asset.preferred), asset.updatedAt.toISOString()] : [assetId, 'missing']); }
    const structural = { assemblyId: assembly.id, assemblyVersion: assembly.version, items: assembly.items.map((item) => ({ videoAssetId: item.videoAssetId, audioAssetId: item.audioAssetId, startMs: item.startMs, endMs: item.endMs, trimInMs: item.trimInMs, trimOutMs: item.trimOutMs })), assetStates, assemblyReview: [assembly.reviewState, assembly.reviewedAt?.toISOString()], exportJobId: exportJob.id, exportVersion: exportJob.exportVersion, exportApproval: [exportJob.approvalState, exportJob.approvedBy, exportJob.approvedAt?.toISOString()], checksum: exportJob.checksum, completedAt: exportJob.completedAt.toISOString(), caption: caption ? [caption.id, caption.version, caption.reviewStatus, caption.preferred, caption.updatedAt.toISOString()] : undefined, rights: rightsAttestations };
    const inputHash = createHash('sha256').update(stableExportSerialize(structural)).digest('hex'); const history = await this.repository.listEpisodeLaunchPackages(seriesId, episodeId); const duplicate = history.find((value) => value.inputHash === inputHash && value.status !== 'rejected'); if (duplicate) return duplicate;
    const version = history.reduce((maximum, value) => Math.max(maximum, value.version), 0) + 1; const now = this.now(); const packageId = `launch_${episodeId}_v${version}`;
    const manifest: DeliveryManifest = { id: `manifest_${episodeId}_v${version}`, manifestVersion: '1.0', seriesId, episodeId, assemblyId: assembly.id, assemblyVersion: assembly.version, exportJobId: exportJob.id, exportVersion: exportJob.exportVersion, outputId: `output_${exportJob.id}`, outputFormat: exportJob.outputFormat, width: exportJob.width, height: exportJob.height, aspectRatio: exportJob.aspectRatio, videoCodec: exportJob.videoCodec, audioCodec: exportJob.audioCodec, durationMs: exportJob.durationMs, fileSize: exportJob.fileSize, checksum: exportJob.checksum, captionMode: exportJob.captionMode, captionSidecarUri: exportJob.sidecarUri, completedAt: exportJob.completedAt, approvalState: 'approved', safeOutputUri: exportJob.outputUri, createdAt: now };
    const value: EpisodeLaunchPackage = { id: packageId, seriesId, episodeId, version, inputHash, status: readinessSnapshot.ready ? 'awaiting_approval' : 'draft', preferred: false, preparedBy: user.id, explanation: `Internal launch handoff for approved episode export ${exportJob.id}.`, seriesTitle: series.title, episodeNumber: episode.episodeNumber, episodeTitle: episode.title, manifest, approvedAssetIds: [...new Set(assembly.items.flatMap((item) => [item.videoAssetId, item.audioAssetId]).filter((id): id is string => Boolean(id)))], captionTrackId: assembly.captionTrackId, captionSidecarUri: exportJob.sidecarUri, rightsAttestations, approvalSummary: { assemblyApprovedBy: assembly.reviewedBy, exportApprovedBy: exportJob.approvedBy }, continuitySummary: { checkedShots: assembly.items.length, blockingViolations: readinessSnapshot.checks.filter((check) => check.id.endsWith('continuity.blocking') && check.status === 'fail').length, warningViolations: readinessSnapshot.checks.filter((check) => check.id.endsWith('continuity.warnings') && check.status === 'warning').length }, readinessSnapshot, approvalHistory: [], validatedAt: now, requestedAt: readinessSnapshot.ready ? now : undefined, createdAt: now, updatedAt: now };
    const created = await this.repository.createEpisodeLaunchPackage(value); this.logger.write({ event: 'launch_package_prepared', seriesId, episodeId, resourceId: created.id, actorId: user.id, status: created.status, blockingCount: readinessSnapshot.blockingCount, warningCount: readinessSnapshot.warningCount }); return created;
  }

  async validate(user: AuthenticatedUser, seriesId: string, episodeId: string, packageId: string): Promise<EpisodeLaunchPackage> {
    await this.requireEpisode(user, seriesId, episodeId, 'VIEWER'); const value = await this.requirePackage(seriesId, episodeId, packageId); if (value.status === 'launch_ready' || value.status === 'rejected') return value;
    const current = await this.prepareFingerprint(user, seriesId, episodeId); if (current !== value.inputHash) throw new Error('Launch inputs changed; prepare a new package version');
    const readinessSnapshot = await this.readiness.episode(user, seriesId, episodeId); const now = this.now(); return this.repository.updateEpisodeLaunchPackage({ ...value, readinessSnapshot, status: readinessSnapshot.ready ? 'awaiting_approval' : 'draft', validatedAt: now, requestedAt: readinessSnapshot.ready ? value.requestedAt || now : undefined, updatedAt: now });
  }

  async approve(user: AuthenticatedUser, seriesId: string, episodeId: string, packageId: string, note: string): Promise<EpisodeLaunchPackage> { await this.requireEpisode(user, seriesId, episodeId, 'OWNER'); const value = await this.validate(user, seriesId, episodeId, packageId); if (value.status !== 'awaiting_approval' || !value.readinessSnapshot.ready) throw new Error('Launch readiness must pass before approval'); const now = this.now(); const approval = { id: `${packageId}_approval_${value.approvalHistory.length + 1}`, packageId, actorId: user.id, decision: 'approved' as const, note, decidedAt: now }; const approved = await this.repository.updateEpisodeLaunchPackage({ ...value, status: 'launch_ready', approvalSummary: { ...value.approvalSummary, launchApprovedBy: user.id }, approvalHistory: [...value.approvalHistory, approval], approvedAt: now, updatedAt: now }); this.logger.write({ event: 'launch_package_approved', seriesId, episodeId, resourceId: packageId, actorId: user.id, status: approved.status }); return approved; }
  async reject(user: AuthenticatedUser, seriesId: string, episodeId: string, packageId: string, note: string): Promise<EpisodeLaunchPackage> { await this.requireEpisode(user, seriesId, episodeId, 'OWNER'); const value = await this.requirePackage(seriesId, episodeId, packageId); if (value.status === 'launch_ready' || value.status === 'rejected') throw new Error('Launch package decision is already final'); const now = this.now(); const approval = { id: `${packageId}_approval_${value.approvalHistory.length + 1}`, packageId, actorId: user.id, decision: 'rejected' as const, note, decidedAt: now }; const rejected = await this.repository.updateEpisodeLaunchPackage({ ...value, status: 'rejected', approvalHistory: [...value.approvalHistory, approval], rejectedAt: now, updatedAt: now }); this.logger.write({ event: 'launch_package_rejected', seriesId, episodeId, resourceId: packageId, actorId: user.id, status: rejected.status }); return rejected; }
  async setPreferred(user: AuthenticatedUser, seriesId: string, episodeId: string, packageId: string): Promise<EpisodeLaunchPackage> { await this.requireEpisode(user, seriesId, episodeId, 'OWNER'); const value = await this.requirePackage(seriesId, episodeId, packageId); if (value.status !== 'launch_ready') throw new Error('Only a launch-ready package can be preferred'); const now = this.now(); for (const current of await this.repository.listEpisodeLaunchPackages(seriesId, episodeId)) if (current.preferred && current.id !== packageId) await this.repository.updateEpisodeLaunchPackage({ ...current, preferred: false, supersededAt: now, updatedAt: now }); return this.repository.updateEpisodeLaunchPackage({ ...value, preferred: true, updatedAt: now }); }

  private async prepareFingerprint(user: AuthenticatedUser, seriesId: string, episodeId: string): Promise<string> {
    const assembly = preferredApprovedAssembly(await this.repository.listEpisodeAssemblies(seriesId, episodeId)); if (!assembly) throw new Error('An approved, valid preferred assembly is required');
    const exportJob = (await this.repository.listEpisodeExportJobs(seriesId, episodeId)).filter((job) => job.assemblyId === assembly.id && job.status === 'completed').sort((a, b) => b.exportVersion - a.exportVersion)[0]; if (!exportJob?.checksum || !exportJob.completedAt || !exportJob.fileSize) throw new Error('A completed approved export with delivery metadata is required');
    const caption = assembly.captionTrackId ? await this.repository.getCaptionTrack(seriesId, episodeId, assembly.captionTrackId) : undefined; const rightsAttestations = await this.readiness.rightsAttestations(user, seriesId); const assetStates: Array<Array<string | number | boolean>> = [];
    for (const item of assembly.items) for (const assetId of [item.videoAssetId, item.audioAssetId]) if (assetId) { const asset = await this.repository.getGeneratedAsset(seriesId, episodeId, item.sceneId, item.shotId, assetId); assetStates.push(asset ? [asset.id, asset.version, asset.reviewStatus, Boolean(asset.preferred), asset.updatedAt.toISOString()] : [assetId, 'missing']); }
    const structural = { assemblyId: assembly.id, assemblyVersion: assembly.version, items: assembly.items.map((item) => ({ videoAssetId: item.videoAssetId, audioAssetId: item.audioAssetId, startMs: item.startMs, endMs: item.endMs, trimInMs: item.trimInMs, trimOutMs: item.trimOutMs })), assetStates, assemblyReview: [assembly.reviewState, assembly.reviewedAt?.toISOString()], exportJobId: exportJob.id, exportVersion: exportJob.exportVersion, exportApproval: [exportJob.approvalState, exportJob.approvedBy, exportJob.approvedAt?.toISOString()], checksum: exportJob.checksum, completedAt: exportJob.completedAt.toISOString(), caption: caption ? [caption.id, caption.version, caption.reviewStatus, caption.preferred, caption.updatedAt.toISOString()] : undefined, rights: rightsAttestations };
    return createHash('sha256').update(stableExportSerialize(structural)).digest('hex');
  }
  private async requireEpisode(user: AuthenticatedUser, seriesId: string, episodeId: string, role: 'OWNER' | 'VIEWER'): Promise<void> { await this.production.authorizeMediaOperation(user, seriesId, role); if (!(await this.repository.getEpisode(seriesId, episodeId))) throw new Error(`Episode ${episodeId} was not found`); }
  private async requirePackage(seriesId: string, episodeId: string, packageId: string): Promise<EpisodeLaunchPackage> { const value = await this.repository.getEpisodeLaunchPackage(seriesId, episodeId, packageId); if (!value) throw new Error(`Episode launch package ${packageId} was not found`); return value; }
}
