'use client';

import { useEffect, useState } from 'react';
import { Captions, Check, Crown, Download, Headphones, Play, RefreshCw, RotateCcw, Volume2, X } from 'lucide-react';

type ShotDialogue = { id: string; shotNumber: number; title?: string; dialogue?: string; characterIds: string[] };
type AudioJob = { id: string; shotId: string; characterId?: string; providerVoiceId?: string; provider: string; providerModel?: string; status: string; promptSnapshot: string; estimatedCost: number; actualCost: number; durationSeconds: number; providerJobId?: string; errorCode?: string; errorMessage?: string; outputAssetIds: string[] };
type AudioAsset = { id: string; generationJobId: string; shotId: string; characterId?: string; providerVoiceId?: string; provider: string; providerModel?: string; uri: string; mimeType: string; codec?: string; sampleRate?: number; bitrate?: number; channels?: number; durationSeconds?: number; version: number; preferred?: boolean; reviewStatus: string; sourceTextSnapshot?: string; costMetadata?: { estimatedCost: number; actualCost: number } };
type CharacterVoice = { id: string; name: string; voiceProfile: { displayName?: string; providerVoiceId?: string; provider?: string; language?: string; locale?: string; active?: boolean } };
type CaptionSegment = { id: string; sequence: number; startMs: number; endMs: number; text: string; speaker?: string };
type CaptionTrack = { id: string; language: string; format: 'srt' | 'vtt'; version: number; reviewStatus: string; preferred: boolean; segments: CaptionSegment[] };
type AudioState = { jobs: AudioJob[]; assets: AudioAsset[]; characters: CharacterVoice[] };

function money(value?: number): string { return value && value > 0 ? `$${value.toFixed(4)}` : '$0.0000'; }
function seconds(ms: number): string { return `${(ms / 1000).toFixed(2)}s`; }
async function responseMessage(response: Response, fallback: string): Promise<string> { try { const body = await response.json(); return body.error?.message || fallback; } catch { return fallback; } }
async function fetchPanelState(audioUrl: string, captionsUrl: string): Promise<{ audio: AudioState; tracks: CaptionTrack[] }> {
  const [audioResponse, captionResponse] = await Promise.all([fetch(audioUrl), fetch(captionsUrl)]);
  if (!audioResponse.ok) throw new Error(await responseMessage(audioResponse, 'Unable to load audio state.'));
  if (!captionResponse.ok) throw new Error(await responseMessage(captionResponse, 'Unable to load caption state.'));
  return { audio: (await audioResponse.json()).data, tracks: (await captionResponse.json()).data };
}

export function AudioCaptionPanel({ seriesId, episodeId, sceneId, shots }: { seriesId: string; episodeId: string; sceneId: string; shots: ShotDialogue[] }) {
  const audioBase = `/api/series/${seriesId}/episodes/${episodeId}/scenes/${sceneId}/audio`;
  const captionsBase = `/api/series/${seriesId}/episodes/${episodeId}/captions`;
  const [audio, setAudio] = useState<AudioState>({ jobs: [], assets: [], characters: [] });
  const [tracks, setTracks] = useState<CaptionTrack[]>([]);
  const [busy, setBusy] = useState('');
  const [error, setError] = useState('');

  async function load() {
    if (!sceneId || !episodeId) return;
    try { const state = await fetchPanelState(audioBase, captionsBase); setAudio(state.audio); setTracks(state.tracks); setError(''); }
    catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to load audio and caption state.'); }
  }

  useEffect(() => {
    let active = true;
    void fetchPanelState(audioBase, captionsBase).then((state) => { if (active) { setAudio(state.audio); setTracks(state.tracks); setError(''); } }).catch((cause) => { if (active) setError(cause instanceof Error ? cause.message : 'Unable to load audio and caption state.'); });
    return () => { active = false; };
  }, [audioBase, captionsBase]);

  async function prepare(mode: 'line' | 'scene', shotId?: string) { setBusy(`prepare:${shotId || 'scene'}`); setError(''); try { const response = await fetch(audioBase, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(mode === 'scene' ? { mode } : { mode, shotId }) }); if (!response.ok) throw new Error(await responseMessage(response, 'Unable to prepare audio.')); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to prepare audio.'); } finally { setBusy(''); } }
  async function jobAction(job: AudioJob, action: string, body: Record<string, unknown> = {}) { setBusy(`${job.id}:${action}`); setError(''); try { const response = await fetch(`${audioBase}/${job.id}/${action}`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }); if (!response.ok) throw new Error(await responseMessage(response, `Unable to ${action} audio.`)); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : `Unable to ${action} audio.`); } finally { setBusy(''); } }
  async function captionAction(payload: Record<string, unknown>) { setBusy(`caption:${payload.action}`); setError(''); try { const response = await fetch(captionsBase, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(payload) }); if (!response.ok) throw new Error(await responseMessage(response, 'Unable to update captions.')); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Unable to update captions.'); } finally { setBusy(''); } }

  const characterName = (id?: string) => audio.characters.find((character) => character.id === id)?.name || 'Unassigned character';
  const activeShotIds = new Set(audio.jobs.filter((job) => ['awaiting_approval', 'approved', 'queued', 'processing'].includes(job.status)).map((job) => job.shotId));

  return <section className="mt-6 border border-stone-800 bg-stone-900 p-5" aria-label="Voice, audio, and caption review">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="flex items-center gap-2 text-xs uppercase tracking-[0.18em] text-amber-500"><Headphones size={15} /> Voice, audio & captions</p><h3 className="mt-1 text-lg font-semibold">Scene dialogue review</h3></div><div className="flex gap-2"><button onClick={() => prepare('scene')} disabled={!!busy} className="rounded bg-amber-700 px-3 py-2 text-xs disabled:opacity-40">Prepare scene dialogue</button><button onClick={load} disabled={!!busy} className="inline-flex items-center gap-1 rounded border border-stone-700 px-3 py-2 text-xs"><RefreshCw size={12} /> Refresh</button></div></div>
    <p className="mt-2 text-xs text-stone-500">Voice and model selection are server-governed. Each snapshotted line requires owner approval before provider submission; cloned/reference voices also require approved consent and rights metadata.</p>
    {error && <p role="alert" className="mt-3 text-sm text-red-400">{error}</p>}

    <div className="mt-4 space-y-3">{shots.filter((shot) => shot.dialogue).map((shot) => <article key={shot.id} className="border border-stone-800 bg-stone-950 p-3"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-semibold text-amber-200">Line {shot.shotNumber} · {characterName(shot.characterIds[0])}</p><p className="mt-1 text-sm text-stone-300">“{shot.dialogue}”</p></div><button onClick={() => prepare('line', shot.id)} disabled={activeShotIds.has(shot.id) || !!busy} className="inline-flex items-center gap-1 rounded border border-amber-800 px-2 py-1.5 text-xs disabled:opacity-40"><Volume2 size={12} /> {audio.assets.some((asset) => asset.shotId === shot.id) ? 'Regenerate' : 'Prepare line'}</button></div></article>)}</div>

    {audio.jobs.map((job) => <article key={job.id} className="mt-3 border-l-2 border-stone-700 bg-stone-950 p-3"><div className="flex flex-wrap justify-between gap-2"><div><p className="text-sm text-amber-300">{characterName(job.characterId)} · {job.provider} / {job.providerModel || 'default'}</p><p className="mt-1 text-xs text-stone-500">{job.status} · voice {job.providerVoiceId || 'unassigned'} · {job.durationSeconds}s · estimated {money(job.estimatedCost)} · actual {money(job.actualCost)}</p><p className="mt-1 text-xs text-stone-400">{job.promptSnapshot}</p></div><span className="text-[10px] text-stone-600">{job.providerJobId || 'not submitted'}</span></div>{job.errorCode && <p className="mt-2 text-xs text-red-300">{job.errorCode}: {job.errorMessage}</p>}<div className="mt-2 flex flex-wrap gap-2">{job.status === 'awaiting_approval' && <><button onClick={() => jobAction(job, 'approve')} disabled={!!busy} className="rounded bg-emerald-800 px-2 py-1 text-xs">Approve line</button><button onClick={() => jobAction(job, 'reject')} disabled={!!busy} className="rounded border border-red-800 px-2 py-1 text-xs text-red-300">Reject</button></>}{job.status === 'approved' && <button onClick={() => jobAction(job, 'start')} disabled={!!busy} className="inline-flex items-center gap-1 rounded bg-amber-700 px-2 py-1 text-xs"><Play size={11} /> Generate</button>}{['queued', 'processing'].includes(job.status) && <button onClick={() => jobAction(job, 'refresh')} disabled={!!busy} className="rounded border border-stone-700 px-2 py-1 text-xs">Refresh provider</button>}{['failed', 'cancelled'].includes(job.status) && <button onClick={() => jobAction(job, 'retry')} disabled={!!busy} className="inline-flex items-center gap-1 rounded border border-stone-700 px-2 py-1 text-xs"><RotateCcw size={11} /> Retry</button>}</div></article>)}

    {audio.assets.map((asset) => { const job = audio.jobs.find((candidate) => candidate.id === asset.generationJobId); if (!job) return null; const playable = !asset.uri.startsWith('mock://') && !asset.uri.startsWith('fake://'); return <article key={asset.id} className="mt-3 border border-stone-800 bg-stone-950 p-3"><div className="flex flex-wrap justify-between gap-2"><div><p className="text-sm font-semibold text-amber-200">{characterName(asset.characterId)} · audio v{asset.version} {asset.preferred && <Crown size={12} className="ml-1 inline" />}</p><p className="mt-1 text-xs text-stone-500">{asset.provider}/{asset.providerModel} · {asset.mimeType} · {asset.codec || 'codec unavailable'} · {asset.sampleRate || 0} Hz · {asset.bitrate || 0} bps · {asset.channels || 0} ch · {asset.durationSeconds || 0}s</p><p className="mt-1 text-xs text-stone-400">{asset.sourceTextSnapshot}</p></div><span className="text-xs text-stone-400">{asset.reviewStatus} · {money(asset.costMetadata?.actualCost)}</span></div>{playable ? <audio controls preload="metadata" src={asset.uri} className="mt-3 w-full" /> : <p className="mt-3 border border-dashed border-stone-700 p-3 text-xs text-stone-500">Deterministic mock audio metadata — playback unavailable.</p>}<div className="mt-2 flex flex-wrap gap-2"><button onClick={() => jobAction(job, 'asset-approve', { assetId: asset.id, notes: 'Approved in scene audio review.' })} disabled={asset.reviewStatus !== 'pending' || !!busy} className="inline-flex items-center gap-1 rounded bg-emerald-800 px-2 py-1 text-xs disabled:opacity-40"><Check size={11} /> Approve</button><button onClick={() => jobAction(job, 'asset-reject', { assetId: asset.id, rejectionReason: 'Rejected in scene audio review.' })} disabled={asset.reviewStatus !== 'pending' || !!busy} className="inline-flex items-center gap-1 rounded border border-red-800 px-2 py-1 text-xs text-red-300 disabled:opacity-40"><X size={11} /> Reject</button><button onClick={() => jobAction(job, 'preferred', { assetId: asset.id })} disabled={asset.reviewStatus !== 'approved' || asset.preferred || !!busy} className="inline-flex items-center gap-1 rounded border border-amber-700 px-2 py-1 text-xs disabled:opacity-40"><Crown size={11} /> Preferred</button></div></article>; })}

    <div className="mt-6 border-t border-stone-800 pt-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="flex items-center gap-2 text-xs uppercase tracking-[0.16em] text-amber-500"><Captions size={14} /> Episode captions</p><p className="mt-1 text-xs text-stone-500">Deterministic timing from persisted scene and shot durations.</p></div><div className="flex gap-2"><button onClick={() => captionAction({ action: 'generate', language: 'en', format: 'srt' })} disabled={!!busy} className="rounded border border-stone-700 px-2 py-1.5 text-xs">Generate SRT</button><button onClick={() => captionAction({ action: 'generate', language: 'en', format: 'vtt' })} disabled={!!busy} className="rounded border border-stone-700 px-2 py-1.5 text-xs">Generate WebVTT</button></div></div>{tracks.map((track) => <article key={track.id} className="mt-3 border border-stone-800 bg-stone-950 p-3"><div className="flex flex-wrap justify-between gap-2"><p className="text-sm font-semibold text-amber-200">{track.format.toUpperCase()} · {track.language} · v{track.version} {track.preferred && '· preferred'}</p><span className="text-xs text-stone-400">{track.reviewStatus}</span></div><div className="mt-2 max-h-40 overflow-auto text-xs text-stone-400">{track.segments.map((segment) => <p key={segment.id} className="border-b border-stone-900 py-1"><span className="text-stone-600">{seconds(segment.startMs)}–{seconds(segment.endMs)}</span> {segment.speaker && <span className="text-amber-300">{segment.speaker}: </span>}{segment.text}</p>)}</div><div className="mt-2 flex flex-wrap gap-2"><button onClick={() => captionAction({ action: 'approve', trackId: track.id, notes: 'Caption timing reviewed.' })} disabled={track.reviewStatus !== 'pending' || !!busy} className="inline-flex items-center gap-1 rounded bg-emerald-800 px-2 py-1 text-xs disabled:opacity-40"><Check size={11} /> Approve</button><button onClick={() => captionAction({ action: 'reject', trackId: track.id, notes: 'Caption track needs revision.' })} disabled={track.reviewStatus !== 'pending' || !!busy} className="inline-flex items-center gap-1 rounded border border-red-800 px-2 py-1 text-xs text-red-300 disabled:opacity-40"><X size={11} /> Reject</button><button onClick={() => captionAction({ action: 'preferred', trackId: track.id })} disabled={track.reviewStatus !== 'approved' || track.preferred || !!busy} className="inline-flex items-center gap-1 rounded border border-amber-700 px-2 py-1 text-xs disabled:opacity-40"><Crown size={11} /> Preferred</button><a href={`${captionsBase}?trackId=${encodeURIComponent(track.id)}&download=1`} className="inline-flex items-center gap-1 rounded border border-stone-700 px-2 py-1 text-xs"><Download size={11} /> Download</a></div></article>)}</div>
  </section>;
}
