'use client';

import { useEffect, useState } from 'react';
import { Check, Crown, PackageCheck, RefreshCw, ShieldCheck, X } from 'lucide-react';

type LaunchPackage = { id: string; version: number; status: string; preferred: boolean; explanation: string; readinessSnapshot: { ready: boolean; blockingCount: number; warningCount: number }; manifest: { exportJobId: string; outputFormat: string; width: number; height: number; videoCodec: string; audioCodec: string; durationMs: number; checksum: string; captionMode: string; safeOutputUri: string }; rightsAttestations: Array<{ characterName: string; sourceType: string; satisfied: boolean }>; approvalHistory: Array<{ id: string; decision: string; note: string; decidedAt: string }>; createdAt: string; approvedAt?: string };

export function EpisodeLaunchPanel({ seriesId, episodeId }: { seriesId: string; episodeId: string }) {
  const base = `/api/series/${seriesId}/episodes/${episodeId}/launch-packages`; const [packages, setPackages] = useState<LaunchPackage[]>([]); const [error, setError] = useState(''); const [busy, setBusy] = useState('');
  async function load() { const response = await fetch(base, { cache: 'no-store' }); const body = await response.json(); if (!response.ok) throw new Error(body.error?.message || 'Unable to load launch packages'); setPackages(body.data); }
  useEffect(() => { let active = true; void fetch(base, { cache: 'no-store' }).then((value) => value.json()).then((body) => { if (active) setPackages(body.data || []); }).catch(() => { if (active) setError('Unable to load launch packages'); }); return () => { active = false; }; }, [base]);
  async function action(key: string, url: string, body: object = {}) { setBusy(key); try { const response = await fetch(url, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }); const value = await response.json(); if (!response.ok) throw new Error(value.error?.message || 'Launch operation failed'); await load(); setError(''); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Launch operation failed'); } finally { setBusy(''); } }
  const selected = [...packages].sort((a, b) => Number(b.preferred) - Number(a.preferred) || b.version - a.version)[0];
  return <section className="mt-8 border border-stone-800 bg-stone-900 p-5" aria-label="Episode launch package"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="flex items-center gap-2 text-xs uppercase tracking-[0.18em] text-amber-500"><PackageCheck size={14} /> Internal launch handoff</p><h3 className="mt-1 text-xl font-semibold">Delivery manifest & final approval</h3><p className="mt-2 text-xs text-stone-500">Preparation snapshots the final approved export, rights attestations, continuity summary, and readiness evidence. It does not publish externally.</p></div><div className="flex gap-2"><button onClick={() => action('prepare', base)} disabled={!!busy} className="rounded bg-amber-700 px-3 py-2 text-xs disabled:opacity-50">Prepare package</button><button onClick={() => { setBusy('refresh'); void load().catch((cause) => setError(cause.message)).finally(() => setBusy('')); }} disabled={!!busy} className="rounded border border-stone-700 p-2"><RefreshCw size={14} /></button></div></div>{error && <p className="mt-3 text-xs text-red-300">{error}</p>}
    <div className="mt-4 flex flex-wrap gap-2">{packages.map((value) => <span key={value.id} className="border border-stone-700 px-2 py-1 text-xs text-stone-400">v{value.version} · {value.status}{value.preferred ? ' · preferred' : ''}</span>)}</div>{selected && <div className="mt-4 border border-stone-800 bg-stone-950 p-4"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-sm font-semibold text-amber-200">Package v{selected.version} · {selected.status}</p><p className="mt-1 text-xs text-stone-600">Export {selected.manifest.exportJobId} · {selected.manifest.outputFormat.toUpperCase()} · {selected.manifest.width}×{selected.manifest.height} · {selected.manifest.videoCodec}/{selected.manifest.audioCodec} · {selected.manifest.captionMode}</p></div><p className={selected.readinessSnapshot.ready ? 'text-xs text-emerald-300' : 'text-xs text-red-300'}>{selected.readinessSnapshot.ready ? 'Readiness snapshot passed' : `${selected.readinessSnapshot.blockingCount} blockers`} · {selected.readinessSnapshot.warningCount} warnings</p></div><p className="mt-2 text-xs text-stone-500">Duration {(selected.manifest.durationMs / 1000).toFixed(2)}s · checksum {selected.manifest.checksum.slice(0, 12)}…</p><div className="mt-3 flex flex-wrap gap-2">{selected.status !== 'launch_ready' && selected.status !== 'rejected' && <><button onClick={() => action('validate', `${base}/${selected.id}/validate`)} disabled={!!busy} className="inline-flex items-center gap-1 rounded border border-stone-700 px-2 py-1 text-xs"><ShieldCheck size={11} /> Validate</button><button onClick={() => action('approve', `${base}/${selected.id}/approve`, { note: 'Final internal launch handoff approved.' })} disabled={!selected.readinessSnapshot.ready || !!busy} className="inline-flex items-center gap-1 rounded bg-emerald-800 px-2 py-1 text-xs disabled:opacity-40"><Check size={11} /> Approve launch</button><button onClick={() => action('reject', `${base}/${selected.id}/reject`, { note: 'Launch handoff requires revision.' })} disabled={!!busy} className="inline-flex items-center gap-1 rounded border border-red-800 px-2 py-1 text-xs text-red-300"><X size={11} /> Reject</button></>}{selected.status === 'launch_ready' && !selected.preferred && <button onClick={() => action('preferred', `${base}/${selected.id}/preferred`)} disabled={!!busy} className="inline-flex items-center gap-1 rounded border border-amber-700 px-2 py-1 text-xs"><Crown size={11} /> Set preferred</button>}</div></div>}
  </section>;
}
