'use client';

import { useEffect, useState } from 'react';
import { AlertTriangle, CheckCircle2, Gauge, RefreshCw, ShieldAlert, XCircle } from 'lucide-react';

type Check = { id: string; category: string; status: 'pass' | 'warning' | 'fail' | 'not-applicable'; explanation: string; remediation: string; blocking: boolean; affectedResource?: { type: string; id: string; label?: string }; metadata?: Record<string, string | number | boolean> };
type Report = { ready: boolean; blockingCount: number; warningCount: number; passedCount: number; checks: Check[]; checkedAt: string };
type Operations = { counts: Record<string, number>; jobs: Array<{ id: string; kind: string; status: string; stale: boolean; remediation: string; episodeId: string }>; checkedAt: string };

export function LaunchDashboard({ seriesId }: { seriesId: string }) {
  const [state, setState] = useState<{ application: Report; series: Report; operations: Operations }>(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function load() { setBusy(true); try { const [readiness, operations] = await Promise.all([fetch(`/api/series/${seriesId}/launch-readiness`, { cache: 'no-store' }), fetch(`/api/operations?seriesId=${encodeURIComponent(seriesId)}`, { cache: 'no-store' })]); if (!readiness.ok || !operations.ok) throw new Error('Launch status could not be loaded'); const readinessBody = await readiness.json(); setState({ ...readinessBody.data, operations: (await operations.json()).data }); setError(''); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Launch status could not be loaded'); } finally { setBusy(false); } }
  useEffect(() => { let active = true; void Promise.all([fetch(`/api/series/${seriesId}/launch-readiness`, { cache: 'no-store' }).then((value) => value.json()), fetch(`/api/operations?seriesId=${encodeURIComponent(seriesId)}`, { cache: 'no-store' }).then((value) => value.json())]).then(([readiness, operations]) => { if (active) setState({ ...readiness.data, operations: operations.data }); }).catch(() => { if (active) setError('Launch status could not be loaded'); }); return () => { active = false; }; }, [seriesId]);
  const combined = state ? [...state.application.checks, ...state.series.checks] : []; const blockers = combined.filter((check) => check.blocking && check.status === 'fail'); const warnings = combined.filter((check) => check.status === 'warning'); const total = combined.length || 1; const passed = combined.filter((check) => check.status === 'pass').length; const episodeFailures = state?.operations.jobs.filter((job) => job.status === 'failed') || [];
  return <section className="mt-8 border border-stone-800 bg-stone-900 p-5" aria-label="Production launch dashboard">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="flex items-center gap-2 text-xs uppercase tracking-[0.18em] text-amber-500"><Gauge size={15} /> Production launch</p><h2 className="mt-1 text-2xl font-semibold">Launch readiness command center</h2><p className="mt-2 max-w-3xl text-sm text-stone-500">Configuration, governance, episode delivery, and operations are checked without calling paid providers.</p></div><button onClick={load} disabled={busy} className="inline-flex items-center gap-2 rounded border border-stone-700 px-3 py-2 text-xs disabled:opacity-50"><RefreshCw size={13} className={busy ? 'animate-spin' : ''} /> Refresh checks</button></div>
    {error && <p role="alert" className="mt-3 text-sm text-red-300">{error}</p>}
    {state && <><div className="mt-5 grid gap-3 md:grid-cols-4"><Metric label="Overall" value={blockers.length ? 'Blocked' : 'Ready'} tone={blockers.length ? 'bad' : 'good'} /><Metric label="Checklist" value={`${passed} / ${total}`} /><Metric label="Blockers / warnings" value={`${blockers.length} / ${warnings.length}`} /><Metric label="Active / failed jobs" value={`${(state.operations.counts.queued || 0) + (state.operations.counts.processing || 0)} / ${state.operations.counts.failed || 0}`} /></div>
      <div className="mt-3 h-1.5 bg-stone-800"><div className="h-1.5 bg-amber-500" style={{ width: `${Math.round((passed / total) * 100)}%` }} /></div>
      <div className="mt-5 grid gap-5 lg:grid-cols-2"><CheckList title="Blocking launch gates" values={blockers} empty="No blocking readiness gates." /><CheckList title="Warnings and review" values={warnings} empty="No launch warnings." /></div>
      <div className="mt-5 grid gap-5 lg:grid-cols-2"><section><h3 className="text-sm font-semibold text-stone-200">Operations health</h3><div className="mt-2 space-y-2">{state.operations.jobs.filter((job) => job.stale || job.status === 'failed' || job.status === 'queued' || job.status === 'processing').slice(0, 8).map((job) => <div key={job.id} className="border border-stone-800 bg-stone-950 p-3 text-xs"><div className="flex justify-between gap-2"><span>{job.kind} · {job.id}</span><span className={job.stale || job.status === 'failed' ? 'text-red-300' : 'text-amber-300'}>{job.stale ? 'stale' : job.status}</span></div><p className="mt-1 text-stone-600">{job.remediation}</p></div>)}{!episodeFailures.length && !state.operations.jobs.some((job) => job.stale || ['queued', 'processing'].includes(job.status)) && <p className="border border-stone-800 bg-stone-950 p-4 text-xs text-emerald-300">No failed, stale, or active jobs.</p>}</div></section><section><h3 className="text-sm font-semibold text-stone-200">Latest completed exports</h3><div className="mt-2 space-y-2">{state.operations.jobs.filter((job) => job.kind === 'episode-export' && job.status === 'completed').slice(0, 8).map((job) => <div key={job.id} className="flex justify-between border border-stone-800 bg-stone-950 p-3 text-xs"><span>{job.id}</span><span className="text-emerald-300">episode {job.episodeId}</span></div>)}{!state.operations.jobs.some((job) => job.kind === 'episode-export' && job.status === 'completed') && <p className="border border-stone-800 bg-stone-950 p-4 text-xs text-stone-600">No completed exports yet.</p>}</div></section></div>
    </>}
  </section>;
}

function Metric({ label, value, tone }: { label: string; value: string; tone?: 'bad' | 'good' }) { return <div className="border border-stone-800 bg-stone-950 p-3"><p className="text-[10px] uppercase tracking-wider text-stone-600">{label}</p><p className={`mt-1 text-lg ${tone === 'bad' ? 'text-red-300' : tone === 'good' ? 'text-emerald-300' : 'text-stone-200'}`}>{value}</p></div>; }
function CheckList({ title, values, empty }: { title: string; values: Check[]; empty: string }) { return <section><h3 className="text-sm font-semibold text-stone-200">{title}</h3><div className="mt-2 space-y-2">{values.slice(0, 12).map((check) => <div key={check.id} className="flex gap-2 border border-stone-800 bg-stone-950 p-3 text-xs">{check.status === 'fail' ? <XCircle size={14} className="mt-0.5 shrink-0 text-red-400" /> : check.status === 'warning' ? <AlertTriangle size={14} className="mt-0.5 shrink-0 text-amber-400" /> : <CheckCircle2 size={14} className="mt-0.5 shrink-0 text-emerald-400" />}<div><p className="text-stone-300">{check.explanation}</p>{check.metadata && <p className="mt-1 text-stone-500">{Object.entries(check.metadata).map(([key, value]) => `${key}: ${String(value)}`).join(' · ')}</p>}<p className="mt-1 text-stone-600">{check.remediation}</p></div></div>)}{!values.length && <p className="flex items-center gap-2 border border-stone-800 bg-stone-950 p-4 text-xs text-emerald-300"><ShieldAlert size={14} /> {empty}</p>}</div></section>; }
