import { NextResponse } from 'next/server';
import { requireUser } from '@/lib/auth';
import { apiError } from '@/lib/api';
import { productionService } from '@/lib/series';
import { shotPatchSchema, shotReorderSchema } from '@/lib/validation/schemas';

export async function GET(_request: Request, { params }: { params: Promise<{ id: string; episodeId: string; sceneId: string; shotId: string }> }) { try { const { user } = await requireUser(); const { id, episodeId, sceneId, shotId } = await params; const value = (await productionService.listShots(user, id, episodeId, sceneId)).find((shot) => shot.id === shotId); if (!value) throw new Error(`Shot ${shotId} was not found`); return NextResponse.json({ data: value, readiness: await productionService.getShotReadiness(user, id, episodeId, sceneId, shotId) }); } catch (error) { return apiError(error, 'SHOT_GET_FAILED', 'Unable to load shot'); } }
export async function PATCH(request: Request, { params }: { params: Promise<{ id: string; episodeId: string; sceneId: string; shotId: string }> }) { try { const { user } = await requireUser(); const { id, episodeId, sceneId, shotId } = await params; const body = await request.json(); if (body?.shotIds) return NextResponse.json({ data: await productionService.reorderShots(user, id, episodeId, sceneId, shotReorderSchema.parse(body).shotIds) }); return NextResponse.json({ data: await productionService.updateShot(user, id, episodeId, sceneId, shotId, shotPatchSchema.parse(body)) }); } catch (error) { return apiError(error, 'SHOT_UPDATE_FAILED', 'Unable to update shot'); } }
export async function DELETE(_request: Request, { params }: { params: Promise<{ id: string; episodeId: string; sceneId: string; shotId: string }> }) { try { const { user } = await requireUser(); const { id, episodeId, sceneId, shotId } = await params; await productionService.deleteShot(user, id, episodeId, sceneId, shotId); return new NextResponse(null, { status: 204 }); } catch (error) { return apiError(error, 'SHOT_DELETE_FAILED', 'Unable to delete shot'); } }
