import type { AuthenticatedUser } from '@/lib/auth';
import type { PersistenceRepository } from '@/lib/repositories';
import type { GeneratedAsset, MediaReview, MediaReviewInput } from '@/types';
import { ProductionService } from '@/lib/series/service';

export class MediaReviewService {
  private readonly production: ProductionService;
  constructor(private readonly repository: PersistenceRepository) { this.production = new ProductionService(repository); }
  async getShotAssets(user: AuthenticatedUser, ids: string[]): Promise<GeneratedAsset[]> { await this.production.getShotReadiness(user, ids[0], ids[1], ids[2], ids[3]); return this.repository.listGeneratedAssets(ids[0], ids[1], ids[2], ids[3]); }
  async submitReview(user: AuthenticatedUser, ids: string[], assetId: string, status: 'approved' | 'rejected', input: MediaReviewInput = {}): Promise<MediaReview> { await this.production.getSeries(user, ids[0]); const asset = await this.requireAsset(ids, assetId); const readiness = await this.production.getShotReadiness(user, ids[0], ids[1], ids[2], ids[3]); if (status === 'approved' && !readiness.ready) throw new Error(`Continuity/readiness blockers prevent approval: ${readiness.blockers.join(' ')}`); if (status === 'rejected' && !input.rejectionReason) throw new Error('A rejection reason is required'); const now = new Date(); const review: MediaReview = { id: `review_${assetId}_${now.getTime()}`, seriesId: ids[0], episodeId: ids[1], sceneId: ids[2], shotId: ids[3], generationJobId: asset.generationJobId, assetId, reviewerActor: user.id, status, notes: input.notes, rejectionReason: input.rejectionReason, continuityAssessment: readiness.ready ? (readiness.warnings.length ? 'warnings' : 'clear') : 'blocked', createdAt: now, updatedAt: now, reviewedAt: now }; await this.repository.updateGeneratedAsset({ ...asset, reviewStatus: status, updatedAt: now }); return this.repository.createMediaReview(review); }
  async selectPreferredAsset(user: AuthenticatedUser, ids: string[], assetId: string): Promise<GeneratedAsset> { await this.production.getSeries(user, ids[0]); const selected = await this.requireAsset(ids, assetId); if (selected.reviewStatus !== 'approved') throw new Error('Only approved assets can be preferred'); const now = new Date(); for (const asset of await this.getShotAssets(user, ids)) { if (asset.preferred && asset.id !== selected.id) { await this.repository.updateGeneratedAsset({ ...asset, preferred: false, supersededAt: now, reviewStatus: 'rejected', updatedAt: now }); await this.repository.createMediaReview({ id: `review_${asset.id}_superseded`, seriesId: ids[0], episodeId: ids[1], sceneId: ids[2], shotId: ids[3], generationJobId: asset.generationJobId, assetId: asset.id, reviewerActor: user.id, status: 'superseded', continuityAssessment: 'clear', createdAt: now, updatedAt: now, reviewedAt: now }); } } return this.repository.updateGeneratedAsset({ ...selected, preferred: true, updatedAt: now }); }
  async compareAssets(user: AuthenticatedUser, ids: string[], leftId: string, rightId: string): Promise<Record<string, unknown>> { const [left, right] = await Promise.all([this.requireAsset(ids, leftId), this.requireAsset(ids, rightId)]); await this.production.getShotReadiness(user, ids[0], ids[1], ids[2], ids[3]); return { left: { version: left.version, generationJobId: left.generationJobId, provider: left.provider, durationSeconds: left.durationSeconds, resolution: `${left.width}x${left.height}`, reviewStatus: left.reviewStatus, createdAt: left.createdAt }, right: { version: right.version, generationJobId: right.generationJobId, provider: right.provider, durationSeconds: right.durationSeconds, resolution: `${right.width}x${right.height}`, reviewStatus: right.reviewStatus, createdAt: right.createdAt } }; }
  async getReviewHistory(user: AuthenticatedUser, ids: string[], assetId?: string): Promise<MediaReview[]> { await this.production.getShotReadiness(user, ids[0], ids[1], ids[2], ids[3]); return this.repository.listMediaReviews(ids[0], ids[1], ids[2], ids[3], assetId); }
  private async requireAsset(ids: string[], assetId: string): Promise<GeneratedAsset> { const asset = await this.repository.getGeneratedAsset(ids[0], ids[1], ids[2], ids[3], assetId); if (!asset) throw new Error(`Asset ${assetId} was not found`); return asset; }
}
