ALTER TYPE "GenerationJobStatus" ADD VALUE IF NOT EXISTS 'DRAFT';
ALTER TYPE "GenerationJobStatus" ADD VALUE IF NOT EXISTS 'AWAITING_APPROVAL';
ALTER TYPE "GenerationJobStatus" ADD VALUE IF NOT EXISTS 'APPROVED';
ALTER TYPE "GenerationJobStatus" ADD VALUE IF NOT EXISTS 'REJECTED';
